Added `Elsa.Studio.Models` directive
If not added, it would show error:

~\ElsaStudioBlazorWasm\Program.cs(24,28): error CS0246: The type or namespace name 'BackendApiConfig' could not be found (are you missing a using directive or an assembly reference?)

The build failed. Fix the build errors and run again.